---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-yaml
        exclude: ^postal/templates/.*$|^chart-schema.yaml$
      - id: mixed-line-ending
      - id: trailing-whitespace
#      - id: no-commit-to-branch
#        args: [ --branch, main ]
  - repo: https://github.com/tcort/markdown-link-check
    rev: 3c9471f # v3.14.1
    hooks:
      - id: markdown-link-check
        name: markdown link check
        args: [ --quiet, "--config", ".config/markdown-link-check.config.json" ]

#  - repo: https://github.com/jtyr/kubeconform-helm
#    rev: v0.1.17
#    hooks:
#      - id: kubeconform-helm
#        args:
#          - --summary
#          - --strict
#          - --values-dir postal/ci
#  # https://github.com/norwoodj/helm-docs?tab=readme-ov-file#pre-commit-hook
#  - repo: https://github.com/norwoodj/helm-docs
#    rev: "1.14.2"
#    hooks:
#      - id: helm-docs-container
#        args:
#          # Make the tool search for charts only under the `charts` directory
#          - --chart-search-root=resources/charts/stable/mailpit
#  - repo: https://github.com/dadav/helm-schema
#    rev: 0.18.1
#    hooks:
#      - id: helm-schema
#        # for all available options: helm-schema -h
#        args:
#          # directory to search recursively within for charts
#          - --chart-search-root=resources/charts/stable/mailpit
#
#          # don't analyze dependencies
#          # - --no-dependencies
#
#          # Add references line as header in the values.yaml file if not exist
#          # - --add-schema-reference
#
#          # helm docs compat
#          - --helm-docs-compatibility-mode
#
#          # append newline to generated jsonschema at the end of the file
#          - --append-newline
#
#          # list of fields to skip from being created by default
#          # e.g. generate a relatively permissive schema
#          # - "--skip-auto-generation=required,additionalProperties"
